### PR TITLE
Add demangling for `f16` and `f128`

### PR DESCRIPTION
**Pull request by tgross35**
`k` was selected for `f16`/`half` and `q` for `f128`/`quad`.

These are different from LLVM's defaults which are `Dh` for half ([link](https://github.com/llvm/llvm-project/blob/fdef7952cbc26fd31d0d92a4f14dde58bc461fe9/clang/lib/AST/ItaniumMangle.cpp#L3124)) and `g` for quad ([link](https://github.com/llvm/llvm-project/blob/fdef7952cbc26fd31d0d92a4f14dde58bc461fe9/clang/include/clang/Basic/TargetInfo.h#L767)). I don't know if there is any reason to mirror LLVM here because it would mean adding multi character tags for primitives. I just used `q` because it it's more obviously in line with `f` for `float`/`f32` and `d` for `double`/`f64`.

Part of https://github.com/rust-lang/rust/pull/114607

### CODE REVIEW

**Comment by tgross35** [comment]
The f16 & f128 RFC was merged so I think it is OK to decide on mangling. Marking it as ready for review @Mark-Simulacrum

**Comment by tgross35** [comment]
@rcvalle / @michaelwoerister,  we need this mangling at some point - any guidance on how to proceed?

Itanium uses `Dh` for `f16` but I think that may conflict with some `dyn` signature.

**Comment by michaelwoerister** [comment]
We'll need to take a look at what the grammar allows. Is this implemented in the compiler already? Will these types be primitive types in Rust?

**Comment by michaelwoerister** [comment]
I just saw the links in the PR message. Will read those 🙂

**Comment by tgross35** [comment]
> We'll need to take a look at what the grammar allows. Is this implemented in the compiler already? Will these types be primitive types in Rust?

The primitives exist in the compiler but not yet fully exposed (https://github.com/rust-lang/rust/pull/121926 coming soon). Currently it does the itanium mangling and just ICEs with v0 mangling.

**Comment by michaelwoerister** [comment]
`k` and `q` seem like good picks to me. 

@ehuss suggested [here](https://github.com/rust-lang/rfcs/pull/3161#issuecomment-1930532909) that we extend mangling scheme by updating the [official docs](https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/symbol-mangling/v0.md). I think that is a good idea. Would you mind opening a PR that adds the two cases to the [basic types section](https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/symbol-mangling/v0.md#basic-type) and then we can do a compiler team FCP to sign off on the change.

**Comment by rcvalle** [comment]
I added a comment at https://github.com/rust-lang/rust/pull/121728#discussion_r1506570300, but this is for CFI encoding and cross-language CFI compatibility and independent/dissociated to Rust mangling/demangling and a different encoding can be used for it.

**Comment by tgross35** [comment]
Thanks for the pointers, I opened https://github.com/rust-lang/rust/pull/122106 to follow up

**Comment by tgross35** [comment]
Totally forgot abut this, thanks!

**Pull request closed without merging**
