### PR TITLE
Add license files into the capi crate tarball

### LINKED ISSUE #72: Include LICENSE files in the published rustc-demangle-capi crate
While the Cargo.toml specifies a license (or licenses), crates also typically include a copy of that license (or licenses) as LICENSE files. This github repo contains the license files but the `rustc-demangle-capi` crate does not.

FWIW the rustc-demangle crate does include the license files. Can they also be included in the rustc-demangle-capi crate?

As a consumer of third party open source libraries, Chromium is aiming to ensure we include the license files in our own source tree for all of our third-party dependencies, and the rustc-demangle-capi crate is one of a few for which they are missing. Chromium issue: [crbug.com/369075726](https://crbug.com/369075726)

### PR DESCRIPTION
**Pull request by danakj**
Symlinks are added up to the license files in the repository root.

This ensures projects that include the source code for this project will also get a copy of the licenses.

Fixes #72.

### CODE REVIEW

**Comment by anforowicz** [comment]
Thanks @Mark-Simulacrum!  Could you please also release a new version (with the license files) to https://crates.io/crates/rustc-demangle-capi/versions?

**Comment by anforowicz** [comment]
@alexcrichton, would it be possible to publish a new version of this crate please (including the PR here with symlinks that help to publish license files)?  This would help Chromium's efforts to automate generation of software-bill-of-materials (SBOM) as tracked in https://crbug.com/378273840.  I see that you are the publisher of [`rustc-demangle-capi`'s only version on crates.io](https://crates.io/crates/rustc-demangle-capi/versions), so I hope that you could help please?

**Comment by alexcrichton** [comment]
I've handed off maintenance of this crate to rust-lang folks, so I would recommend raising this on Zulip perhaps to request a release

**Comment by Mark-Simulacrum** [comment]
published, opened PR to bump the in-tree version number: https://github.com/rust-lang/rustc-demangle/pull/79

**Pull request merged**
